title: ">: extmkv"
baseurl: "" # Leave empty if using a custom domain
url: "https://jcosta.pt"
markdown: kramdown
remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/jorge-costa-pt/" }
    - { platform: github, user_url: "https://github.com/exmtkv" }
    - { platform: x, user_url: "https://x.com/exmtkv" }
  header_pages:
    - about.md