title: ">: extmkv"
baseurl: "" # Leave empty if using a custom domain
url: "https://jcosta.pt"
markdown: kramdown
remote_theme: jekyll/minima

minima:
  skin: dark
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/extmkv"
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/jorge-costa-pt/"
    - title: X
      icon: x-twitter
      url: "https://x.com/extmkv"
  header_pages:
    - about.md